name: 'Auto Release Draft'
description: 'Drafts a Github release with the changes introduce by newly created version tag'
author: 'Felipe'
outputs:
  release-url:
    description: 'The URL of the Github release that was drafted'
runs:
  using: 'node16'
  main: 'dist/index.js'
