name: Build
on: 
  push:
    branches:
      - main
      
jobs:
  build: 
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Restore the dependencies
        run: npm ci
      - name: Build
        run: npm run all
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}